version: '3.7'

services:
  briefings:
    image: briefings
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 6080:8080
        - 6443:443
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - MONGO_DB_CONN_STRING=${MONGO_DB_CONN_STRING}
      - MONGO_DB_URL=mongodb
      - MONGO_DB_PORT=27017
      - MONGO_DB_USERNAME=admin
      - MONGO_DB_PASSWORD=admin
      - MONGO_DB_DATABASE=briefings
    networks:
      - briefings
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=briefings
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - briefings

volumes:
  mongodb:
  mongoconfig:

networks:
  briefings:
    driver: bridge
