services:
  briefings:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 6001:8080
    env_file:
        - .env
    environment:
      - MONGO_DB_URL=mongodb
      - MONGO_DB_PORT=27017
      - MONGO_DB_USERNAME=admin
      - MONGO_DB_PASSWORD=admin
      - MONGO_DB_DATABASE=briefings
    networks:
      - briefings
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=briefings
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - briefings

volumes:
  mongodb:
  mongoconfig:

networks:
  briefings:
    driver: bridge
